language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

notifications:
  email:
    - recipients:
        - andrew.e.kimberly@gmail.com

install:
  - npm install
  - npm run build

script:
  - npm run ci

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_EB_S3_BUCKET # The S3 bucket EB uses to store the application files.
  region: $AWS_REGION
  app: $AWS_EB_APP
  env: $AWS_EB_ENV
  zip_file: './www/Archive.zip'
  skip_cleanup: true
  on:
    tags: true
